// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfjhLmuQa6Atep-QEAptuOw9OWX0TcA1Q',
    appId: '1:304251544044:web:d9590bf8fe398b42d1e0c9',
    messagingSenderId: '304251544044',
    projectId: 'quizzapp-e0e7f',
    authDomain: 'quizzapp-e0e7f.firebaseapp.com',
    storageBucket: 'quizzapp-e0e7f.appspot.com',
    measurementId: 'G-VNMZ6964LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNIes7JcIa8puCJ1yKMi595Wiftm46GPo',
    appId: '1:304251544044:android:e049f0d795ed764ad1e0c9',
    messagingSenderId: '304251544044',
    projectId: 'quizzapp-e0e7f',
    storageBucket: 'quizzapp-e0e7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdpWcYbYtBzTzFNHH5SRUfLuLlNExo_yQ',
    appId: '1:304251544044:ios:13c7d9f33da7c065d1e0c9',
    messagingSenderId: '304251544044',
    projectId: 'quizzapp-e0e7f',
    storageBucket: 'quizzapp-e0e7f.appspot.com',
    iosBundleId: 'com.example.quizzapp',
  );
}
