name: quizzapp
description: "A new Flutter project."

publish_to: 'none' # No publicar este paquete
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.2.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Añadir activos a tu proyecto
  assets:
    - assets/datosBBDD/
    - assets/images/